multitenant:
  tenantKey: x-tenant
  defaultTenant: github
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/testdb
      username: admin
      password: admin
      driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false